### ISSUE TITLE
Consider renaming to speedup-dashboard

### ISSUE THREAD

**Issue by jirutka** [ezrondre/perfdashboard#6]
You have speedup-rails, speedup-adapters and perfdashboard. The last one doesn’t seem to be related to speedup, it’ll be IMO better to rename it to something like speedup-dashboard.

**Comment by ezr-ondrej** [comment]
Yeah, it probably would... I don't know why I haven't thought about it... First thougth was that this gem would be useable for larger set of performance data than those from speedup-rails, but as this is certainly not true now, it is probably better to rename it :)

**Comment by ezr-ondrej** [comment]
I have renamed tables in migrations. Sorry for inconvinience if you have any data in db, but I hope, that it is not problem in this early stage of gem. And migrations looks much cleaner this way than renaming the tables. But I can push a migration which looks if there are those tables and rename them, if you wish :)

**Comment by jirutka** [comment]
It’s no problem for me. :)
